### ISSUE TITLE
Instalation filure (PIP)

### ISSUE THREAD

**Issue by kanyezik** [mertguvencli/deploydb#2]
* deploydb version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by mertguvencli** [comment]
Hey 👋

Please describe your problem to get an understanding of what's wrong.
